#to build 3hdeng/zake-word2vec:2.7
FROM python:2.7
MAINTAINER 3hdeng
#====================
RUN pip install -U pip
RUN pip install -U gensim

#================
RUN pip install jieba
#RUN pip install joblib

#=======
# Make sure you have a C compiler before installing gensim, to use optimized (compiled) word2vec training (70x speedup compared to plain NumPy implementation
RUN apt-get update &&  apt-get install -y make
RUN apt-get install -y gcc libc6-dev

ENV PYTHONIOENCODING UTF-8

CMD []
